"""add composite index on claims member_id status created_at

Revision ID: bc01b57619d4
Revises: 10759c509166
Create Date: 2026-09-13 14:45:49.702260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc01b57619d4'
down_revision: Union[str, Sequence[str], None] = '10759c509166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_claims_member_status_created', 'claims', ['member_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_claims_member_status_created', table_name='claims')
    # ### end Alembic commands ###
